spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/Coding/inflearn/스프링 JPA 활용/springJPA1/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true //System.out.println()? ???? ???
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug